<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Extent Test Suite" duration-ms="142" started-at="2022-12-16T23:23:42 IST" finished-at="2022-12-16T23:23:42 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="142" started-at="2022-12-16T23:23:42 IST" finished-at="2022-12-16T23:23:42 IST">
      <class name="test2.Test1">
        <test-method status="PASS" signature="setUp()[pri:0, instance:test2.Test1@67e2d983]" name="setUp" is-config="true" duration-ms="12" started-at="2022-12-16T23:23:42 IST" finished-at="2022-12-16T23:23:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="login()[pri:0, instance:test2.Test1@67e2d983]" name="login" duration-ms="22" started-at="2022-12-16T23:23:42 IST" finished-at="2022-12-16T23:23:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="logOut()[pri:1, instance:test2.Test1@67e2d983]" name="logOut" duration-ms="5" started-at="2022-12-16T23:23:42 IST" finished-at="2022-12-16T23:23:42 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Logout Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Logout Failed
at org.testng.Assert.fail(Assert.java:99)
at test2.Test1.logOut(Test1.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOut -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test2.Test1@67e2d983]" name="tearDown" is-config="true" duration-ms="1" started-at="2022-12-16T23:23:42 IST" finished-at="2022-12-16T23:23:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test2.Test1 -->
    </test> <!-- Test -->
  </suite> <!-- Extent Test Suite -->
</testng-results>
